name: Check Upstream Updates

on:
  workflow_dispatch:      # Manual trigger

jobs:
  check-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: define environment variables
        run: |
          echo "UPSTREAM_REPO=St-Pavlov-Foundation/re1999-data" >> $GITHUB_ENV
          echo "UPSTREAM_BRANCH=main" >> $GITHUB_ENV
          echo "LAST_COMMIT_FILE=.last_upstream_commit" >> $GITHUB_ENV

      - name: get latest upstream commit hash
        id: get_latest
        run: |
          latest_commit=$(git ls-remote https://github.com/${{ env.UPSTREAM_REPO }} refs/heads/${{ env.UPSTREAM_BRANCH }} | cut -f1)
          echo "latest_commit=$latest_commit" >> $GITHUB_OUTPUT

      - name: load previous commit hash
        id: check_previous
        run: |
          if [ -f "${{ env.LAST_COMMIT_FILE }}" ]; then
            prev_commit=$(cat "${{ env.LAST_COMMIT_FILE }}")
          else
            prev_commit=""
          fi
          echo "prev_commit=$prev_commit" >> $GITHUB_OUTPUT

      - name: compare hashes
        id: compare
        run: |
          if [ "${{ steps.get_latest.outputs.latest_commit }}" != "${{ steps.check_previous.outputs.prev_commit }}" ]; then
            echo "updated=true" >> $GITHUB_OUTPUT
          else
            echo "updated=false" >> $GITHUB_OUTPUT
          fi

      - name: trigger json update
        if: steps.compare.outputs.updated == 'true'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            https://api.github.com/repos/myssal/IdJsonGenerator/dispatches \
            -d '{"event_type":"upstream_update"}'

      - name: save new commit hash (if updated)
        if: steps.compare.outputs.updated == 'true'
        run: |
          echo "${{ steps.get_latest.outputs.latest_commit }}" > "${{ env.LAST_COMMIT_FILE }}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${{ env.LAST_COMMIT_FILE }}"
          git commit -m "Update upstream commit hash"
          git push
